### ISSUE TITLE
Glyphicons Not Loading

### ISSUE THREAD

**Issue by cdburgess** [Rhym/cakeStrap#19]
I cannot figure out why, but the GlyphIcons are not loading in the page views.

**Comment by Rhym** [comment]
Anything in the console?

**Comment by cdburgess** [comment]
Nothing is being reported there, no.

**Comment by giraam** [comment]
I'm having the exact same problem. I'll let you know if I can find something.

**Comment by Rhym** [comment]
Hmm, I'm going to upgrade CakeStrap this weekend to the latest version of bootstrap. So I'll address the issue in the new branch.
