### ISSUE TITLE
URL rewriting - issue

### ISSUE THREAD

**Issue by pekez** [Rhym/cakeStrap#2]
Hi, I've installed CakePHP v2.3.1, and after implementing CakeStrap, I got this message:

URL rewriting is not properly configured on your server.

Is there any solution for this issue.

Thanks a lot.

**Comment by AlexSnowLeo** [comment]
I confirm that I have the same

**Comment by Rhym** [comment]
Sounds like you haven't enabled your database in \app\Config. Make sure you have removed .default from the end of the file and entered your database details.

**Comment by amykhar** [comment]
Nope. The database is configured and working properly.  If I comment out using the theme, all is well.  If I enable CakeStrap, I get that error.

**Comment by c88lopez** [comment]
Any news on this case? I have the same issue... It seems to be something with the .htaccess

**Comment by Rhym** [comment]
I can't seem to replicate this, can someone send me a zip file of their app and database?

**Comment by amykhar** [comment]
I deleted mine already, but all it was was a clean installation of the latest version of cake 2, with an empty database and the config settings (salt, timezone, etc.) modified as necessary to be able to see the default cake home page. If I install and enable the plugin, I get the warning about clean urls.  If I disable the plugin, the warning goes away.  I am on OSX with the default version of php, apache, etc. that comes with Mountain Lion.

**Comment by ghost** [comment]
Same problem.

**Comment by ebosveld** [comment]
The default theme sets the div with ID url-rewriting-warning on display:none by default in cake.generic.css. So it is only shown when there is actually something wrong. For some reason it does not get set in the cakestrap theme. I think it's save to ignore it, but you can add the following code to the core.css in the cakestrap folder.

``` css
#url-rewriting-warning {
    display: none;
}
```

**Comment by kylescottmcgill** [comment]
I have just installed this with a clean install of CakePHP, and i can confirm that it all works as advertised. @amykhar Mac OSX's Apache doesn't have mod_rewrite enabled by default this is something you will need to change, you will also need to allow it to use the htaccess file that comes with CakePHP. More Info: http://book.cakephp.org/2.0/en/installation/url-rewriting.html

I assume however that most people using this are seasoned Web Developers or Cake enthusiast so does anyone have any error messages? Im not a Cake Expert, but in the 5 mins worth of setup i was able to get my routes setup, and some quick controller actions and all worked as expected.

**Comment by amykhar** [comment]
Mod Rewrite is enabled and working properly.  I've been using Cake 1.3 for more than two years now and am well versed in the configuration of it. :)  I believe ebosveld is correct and that the rewriting is working as intended, but that the div with the warning message is not being properly hidden.

**Comment by kylescottmcgill** [comment]
Hey @amykhar i figured everyone would be Cake veterans :P hmmm maybe i missed something in my implementation, and therefore i was never presented with the error message.

**Comment by Rhym** [comment]
Had a look into it, and ebosveld was right - Cake displays this when there's an issue, but hides it by default (Odd if you ask me, but anyway). I added a line to the core.css to fix this. Thanks Kyle for having a look around :)
