### ISSUE TITLE
Bake pagination code correct

### ISSUE THREAD

**Issue by AlexSnowLeo** [Rhym/cakeStrap#3]
I'm encountered an error while generating code in View section Paginate in Paginator->number() function. Incorrect added a span tag.
Here is the correct code:
<code>echo $this->Paginator->numbers(array('separator' => '', 'currentTag' => 'a', 'tag' => 'li', 'currentClass' => 'disabled'));</code>

**Comment by Rhym** [comment]
The pull request doesn't fix the problem unfortunately, it seems like "disabledTag" isn't working properly.
