### ISSUE TITLE
add to the project theme Plusstrap

### ISSUE THREAD

**Issue by AlexSnowLeo** [Rhym/cakeStrap#5]
As you look at it, to add to the project theme Plusstrap?
It is made on the basis of bootstrap, but has a design similar to Google.
http://xbreaker.github.io/plusstrap/

**Comment by Rhym** [comment]
I don't believe so, it hasn't been active in over 8 months, and really all it does is remove all of the corner radius from the elements, and change the button colours.

**Comment by AlexSnowLeo** [comment]
I asked once and for good reason. Would not you just add more themes Bootstrap to your project? As CSS with the ability to switch between them, as implemented here: 
https://github.com/hugodias/cakeStrap/tree/master/app/webroot/css
